# Typekit
typekit_id: rhz7zis

slogan:
  title: Aotokitsuruya
  description: The Web is attracting  me, so I start learning PHP, HTML, CSS and JavaScript. When I know about Ruby, I fall in love with it. Now, I working with my friend to design games using C++ and still learning web about Golang, Ruby and JavaScript. In the other side, I also be a designer, the reason why the web is attracted me.

excerpt_link: 繼續閱讀
