baseURL = "https://blog.frost.tw/"
languageCode = "zh-TW"
title = "弦而時習之"
theme = "air"
DefaultContentLanguage = "zh-tw"
hasCJKLanguage = true
disablePathToLower = true
disqusShortname = "revo-skill-frost"
rssLimit = 10

[author]
  name = "蒼時弦也"
  email = "contact@frost.tw"

[params]
  author = "蒼時弦也"
  title = "弦而時習之"
  subtitle = "蒼時弦也的程式筆記"
  description = "蒼時弦也的個人網誌，專注在前端、後端以及遊戲開發，大多使用 Ruby 和 Ruby on Rails 以及 Golang、JS 和 C 語言。"
  cover = "http://blog.frost.tw/icon-512.png"
  themecolor = "#EFEFEF"
  tag_manager = "GTM-5TQLRN"
  facebook_app_id = "178355449110"

[frontmatter]
date = [":filename", ":default"]

[permalinks]
posts = "/posts/:year/:month/:day/:slug"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.zh-tw]
    contentDir = "content/zh-tw"
    languageName = "繁體中文"
    weight = 1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "solarized-dark"
    tabWidth = 2
